# Generated by Django 5.2.12 on 2026-03-12 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('end_demand', models.IntegerField(default=0)),
                ('lot_size', models.IntegerField(default=1)),
                ('transfer_batch', models.IntegerField(default=-1)),
                ('department_area', models.CharField(blank=True, max_length=255, null=True)),
                ('demand_factor', models.FloatField(default=1)),
                ('lot_factor', models.FloatField(default=1)),
                ('variability_factor', models.FloatField(default=1)),
                ('make_to_stock', models.BooleanField(default=False)),
                ('gather_transfer_batches', models.BooleanField(default=False)),
                ('prod1', models.FloatField(default=0)),
                ('prod2', models.FloatField(default=0)),
                ('prod3', models.FloatField(default=0)),
                ('prod4', models.FloatField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organizations.organization')),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['organization', 'department_area'], name='products_organiz_798a37_idx'), models.Index(fields=['organization', 'created_at'], name='products_organiz_d506c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_product_per_org')],
            },
        ),
    ]
