# Generated by Django 5.2.12 on 2026-03-13 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
        ('rmct', '0002_remove_rmcmmodel_equipment_remove_rmcmmodel_general_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_per_org',
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='rmct.rmcmmodel'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model', 'created_at'], name='products_model_i_3e1d77_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('organization', 'model', 'name'), name='unique_product_per_org_model'),
        ),
    ]
