# Generated by Django 5.2.12 on 2026-03-12 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rmct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_title', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('ops_time_unit', models.CharField(choices=[('SEC', 'Seconds'), ('MIN', 'Minutes'), ('HR', 'Hours')], default='MIN', max_length=4)),
                ('mct_time_unit', models.CharField(choices=[('MIN', 'Minutes'), ('HR', 'Hours'), ('DAY', 'Days'), ('WEEK', 'Weeks')], default='DAY', max_length=5)),
                ('prod_period_unit', models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='YEAR', max_length=5)),
                ('conv1', models.FloatField(default=480)),
                ('conv2', models.FloatField(default=210)),
                ('util_limit', models.FloatField(default=95.0)),
                ('var_equip', models.FloatField(default=30.0)),
                ('var_labor', models.FloatField(default=30.0)),
                ('var_prod', models.FloatField(default=30.0)),
                ('gen1', models.FloatField(default=0.0)),
                ('gen2', models.FloatField(default=0.0)),
                ('gen3', models.FloatField(default=0.0)),
                ('gen4', models.FloatField(default=0.0)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_settings', to='rmct.rmcmmodel')),
            ],
            options={
                'verbose_name': 'General data',
                'verbose_name_plural': 'General data',
                'db_table': 'general_data',
            },
        ),
    ]
