# Generated by Django 5.2.12 on 2026-03-12 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('probability', models.FloatField(default=1)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('from_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_steps', to='operations.operation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='products.product')),
                ('to_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_steps', to='operations.operation')),
            ],
            options={
                'db_table': 'routing',
                'indexes': [models.Index(fields=['product'], name='routing_product_574925_idx'), models.Index(fields=['organization', 'product'], name='routing_organiz_a3d2a0_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_operation', 'to_operation'), name='unique_operation_path')],
            },
        ),
    ]
