# Generated by Django 5.2.12 on 2026-03-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('organizations', '0001_initial'),
        ('products', '0002_remove_product_unique_product_per_org_product_model_and_more'),
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='routing',
            name='unique_operation_path',
        ),
        migrations.AddConstraint(
            model_name='routing',
            constraint=models.UniqueConstraint(fields=('product', 'from_operation', 'to_operation'), name='unique_operation_path'),
        ),
    ]
