# Generated by Django 5.2.12 on 2026-03-12 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labor', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=1)),
                ('mttf_minutes', models.IntegerField(default=0)),
                ('mttr_minutes', models.IntegerField(default=0)),
                ('overtime_percent', models.FloatField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('equipment_type', models.CharField(default='Standard', max_length=50)),
                ('percent_time_unavailable', models.FloatField(default=0)),
                ('setup_factor', models.FloatField(default=1)),
                ('run_factor', models.FloatField(default=1)),
                ('variability_factor', models.FloatField(default=1)),
                ('department_area', models.CharField(blank=True, max_length=255, null=True)),
                ('out_of_area_equipment', models.BooleanField(default=False)),
                ('eq1', models.FloatField(default=0)),
                ('eq2', models.FloatField(default=0)),
                ('eq3', models.FloatField(default=0)),
                ('eq4', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('labor_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_groups', to='labor.labor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_groups', to='organizations.organization')),
            ],
            options={
                'db_table': 'equipment_groups',
                'indexes': [models.Index(fields=['organization', 'department_area'], name='equipment_g_organiz_86b627_idx'), models.Index(fields=['organization', 'created_at'], name='equipment_g_organiz_567d3c_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_equipment_group_per_org')],
            },
        ),
    ]
