# Generated by Django 5.2.12 on 2026-03-12 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=1)),
                ('overtime_percent', models.FloatField(default=0)),
                ('unavailability_percent', models.FloatField(default=0)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('setup_factor', models.FloatField(default=1)),
                ('run_factor', models.FloatField(default=1)),
                ('variable_factor', models.FloatField(default=1)),
                ('prioritize', models.BooleanField(db_index=True, default=False)),
                ('lab1', models.FloatField(blank=True, null=True)),
                ('lab2', models.FloatField(blank=True, null=True)),
                ('lab3', models.FloatField(blank=True, null=True)),
                ('lab4', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labors', to='organizations.organization')),
            ],
            options={
                'db_table': 'labors',
                'indexes': [models.Index(fields=['organization', 'department'], name='labors_organiz_85edd0_idx'), models.Index(fields=['organization', 'created_at'], name='labors_organiz_810e66_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_labor_name_per_org')],
            },
        ),
    ]
