# Generated by Django 5.2.12 on 2026-03-12 07:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_per_assembly', models.FloatField(default=1)),
                ('position', models.IntegerField(default=1)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='products.product')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='organizations.organization')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.product')),
            ],
            options={
                'db_table': 'bom',
                'indexes': [models.Index(fields=['organization', 'parent_product'], name='bom_organiz_0bbf8f_idx'), models.Index(fields=['component_product'], name='bom_compone_e5a46f_idx')],
                'constraints': [models.UniqueConstraint(fields=('parent_product', 'component_product'), name='unique_component_per_parent')],
            },
        ),
    ]
