# Generated by Django 5.2.12 on 2026-03-12 06:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_organization(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    default_id = uuid.UUID("00000000-0000-0000-0000-000000000001")
    if not Organization.objects.filter(pk=default_id).exists():
        Organization.objects.create(
            pk=default_id,
            name="Default Organization",
            organization_code="DEFAULT",
            slug="default",
            status=1,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_default_organization, migrations.RunPython.noop),
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(default=uuid.UUID('00000000-0000-0000-0000-000000000001'), on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(db_index=True, default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['organization', 'role'], name='user_profil_organiz_5c8824_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['organization', 'created_at'], name='user_profil_organiz_95234d_idx'),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
