# Generated by Django 5.2.12 on 2026-03-12 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RMCMModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_status', models.CharField(default='never_run', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_demo', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('general', models.JSONField(default=dict)),
                ('param_names', models.JSONField(default=dict)),
                ('labor', models.JSONField(default=list)),
                ('equipment', models.JSONField(default=list)),
                ('products', models.JSONField(default=list)),
                ('operations', models.JSONField(default=list)),
                ('routing', models.JSONField(default=list)),
                ('ibom', models.JSONField(default=list)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rmct_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='rmct.rmcmmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('family_id', models.UUIDField(blank=True, null=True)),
                ('is_basecase', models.BooleanField(default=False)),
                ('status', models.CharField(default='needs_recalc', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='rmct.rmcmmodel')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioChange',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(max_length=32)),
                ('entity_id', models.CharField(blank=True, max_length=255)),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('basecase_value', models.TextField(blank=True)),
                ('whatif_value', models.TextField(blank=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='rmct.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='rmct.scenario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.UniqueConstraint(condition=models.Q(('is_basecase', True)), fields=('model', 'is_basecase'), name='unique_basecase_per_model'),
        ),
    ]
