# Generated by Django 5.2.12 on 2026-03-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmcmmodel',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='rmcmmodel',
            name='general',
        ),
        migrations.RemoveField(
            model_name='rmcmmodel',
            name='ibom',
        ),
        migrations.RemoveField(
            model_name='rmcmmodel',
            name='labor',
        ),
        migrations.RemoveField(
            model_name='rmcmmodel',
            name='operations',
        ),
        migrations.RemoveField(
            model_name='rmcmmodel',
            name='param_names',
        ),
        migrations.RemoveField(
            model_name='rmcmmodel',
            name='products',
        ),
        migrations.RemoveField(
            model_name='rmcmmodel',
            name='routing',
        ),
    ]
