# Generated by Django 5.2.12 on 2026-03-12 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('labor', '0001_initial'),
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('op_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('percent_assign', models.FloatField(default=100)),
                ('equipment_setup_per_lot', models.FloatField(default=0)),
                ('equipment_run_per_piece', models.FloatField(default=0)),
                ('labor_setup_per_lot', models.FloatField(default=0)),
                ('labor_run_per_piece', models.FloatField(default=0)),
                ('formula_override', models.CharField(blank=True, choices=[('E_SETUP_LOT', 'E.Setup/Lot'), ('E_RUN_PC', 'E.Run/Pc'), ('L_SETUP_LOT', 'L.Setup/Lot'), ('L_RUN_PC', 'L.Run/Pc')], max_length=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('equipment_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='equipment.equipmentgroup')),
                ('labor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='labor.labor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='products.product')),
            ],
            options={
                'db_table': 'operations',
                'indexes': [models.Index(fields=['organization', 'product'], name='operations_organiz_7c05bd_idx'), models.Index(fields=['product', 'op_number'], name='operations_product_45b615_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'op_number'), name='unique_operation_per_product')],
            },
        ),
    ]
