# Generated by Django 5.2.12 on 2026-03-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='equipment_run_per_piece',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='equipment_setup_per_lot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='labor_run_per_piece',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='labor_setup_per_lot',
            field=models.IntegerField(default=0),
        ),
    ]
